# Generated by Django 3.0.7 on 2022-04-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_kurier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kurier',
            old_name='cost',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='kurier',
            old_name='title',
            new_name='name',
        ),
    ]
