# Generated by Django 3.0.7 on 2022-04-28 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20220427_1329'),
        ('orders', '0005_auto_20220427_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='order',
            name='kurier',
        ),
        migrations.AddField(
            model_name='order',
            name='kurier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Kurier'),
        ),
    ]
