# Generated by Django 3.0.7 on 2022-04-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20220428_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='kurier',
            field=models.CharField(choices=[('О', 'Ольга'), ('А', 'Арсений'), ('В', 'Виталий')], default='', max_length=1),
        ),
    ]
