# Generated by Django 3.0.7 on 2022-04-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20220428_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='kurier',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('Ольга', 'Ольга'), ('Арсений', 'Арсений'), ('Виталий', 'Виталий')], verbose_name='month'),
        ),
    ]
